// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSaveFiles: () => typedError<SaveFile[], AppError>(__TAURI_INVOKE("get_save_files")),
	loadSaveFile: (path: string, storefront: Storefront) => typedError<null, AppError>(__TAURI_INVOKE("load_save_file", { path, storefront })),
	getDisplayNames: (storefront: Storefront) => typedError<{ [key in number]: string }, AppError>(__TAURI_INVOKE("get_display_names", { storefront })),
	getCritters: (nowUtcSecs: number) => typedError<Critter[], AppError>(__TAURI_INVOKE("get_critters", { nowUtcSecs })),
	getVillagers: (nowUtcSecs: number) => typedError<Villager[], AppError>(__TAURI_INVOKE("get_villagers", { nowUtcSecs })),
	getToday: (nowUtcSecs: number) => typedError<Today, AppError>(__TAURI_INVOKE("get_today", { nowUtcSecs })),
};

/* Types */
export type AppError = ({ Io: string }) & { NotFound?: never; Parse?: never } | ({ Parse: string }) & { Io?: never; NotFound?: never } | ({ NotFound: string }) & { Io?: never; Parse?: never } | "NoSaveLoaded";

export type CollectionStatus = "inVillage" | "inRealm" | "locked";

export type Critter = {
	itemId: number,
	name: string,
	species: string,
	speciesRank: number,
	note: string | null,
	schedule: Schedule[][],
	availableNow: boolean,
	tamed: boolean,
	fedToday: boolean,
	needsFeeding: boolean,
};

export type PreferredGift = {
	itemId: number,
	name: string,
	discovered: boolean,
	giftedToday: boolean,
};

export type Role = "gardening" | "fishing" | "mining" | "foraging" | "digging";

export type SaveFile = {
	path: string,
	storefront: Storefront,
	lastModified: number,
};

export type Schedule = {
	start: number,
	end: number,
};

export type Section<T> = { status: "ok"; data: T } | { status: "error"; error: string };

export type Storefront = "steam" | "epic" | "microsoft";

export type Today = {
	critters: Section<Critter[]>,
	villagers: Section<Villager[]>,
};

export type Villager = {
	id: number,
	name: string,
	status: CollectionStatus,
	role: Role | null,
	friendshipLevel: number,
	friendshipXp: number,
	isMaxed: boolean,
	gifts: PreferredGift[],
	giftableToday: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

