// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSaveFiles: () => typedError<SaveFile[], AppError>(__TAURI_INVOKE("get_save_files")),
	decryptSaveFile: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("decrypt_save_file", { path })),
	getGameData: (storefront: Storefront) => typedError<{ [key in number]: string }, AppError>(__TAURI_INVOKE("get_game_data", { storefront })),
};

/* Types */
export type AppError = ({ Io: string }) & { Parse?: never } | ({ Parse: string }) & { Io?: never };

export type SaveFile = {
	path: string,
	storefront: Storefront,
	lastModified: number,
};

export type Storefront = "steam" | "epic" | "microsoft";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
